### ISSUE TITLE
[FEATURE] compatibility with advanced enchantments

### ISSUE THREAD

**Issue by Nightkau** [HibiscusMC/HMCWraps#109]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

For some reason, when changing wraps or dropping a tool/sword with a wrap and another player picking it up (and it removing the wrap if they don't have permission for it) any custom enchantments from advanced enchantments will be removed (the visual enchantment lines in the lore only, the actual enchantments remain on the sword)

I don't entirely see this as a bug since it's not necessary for you to make your plugin compatible with all others, for obvious reasons. That being said, since it seems to affect the lore lines only i'm hopeful that it might be a simple fix to make sure all lore lines are kept intact when changing or removing wraps. presumably this would also help with any other plugins that affect the lore lines.

### Config Changes

i don't see that this would need any changes within the config 

### How significant is the feature?

Meerly Significant - Small feature fitting perfectly into the current structure

**Comment by Skyslycer** [comment]
A similar bug has been reported. If the lore isn't changed in the config this shouldn't even happen. Will fix ASAP.

**Comment by dinobossytnew** [comment]
+1

**Comment by Skyslycer** [comment]
Should be fixed in 1.4.1. Can you try it please? Make sure you have lore preservation enabled and aren't overwriting it with `wrap-lore`.

**Comment by Skyslycer** [comment]
Should be fixed in 1.4.1. Can you try it please? Make sure you have lore preservation enabled and aren't overwriting it with `wrap-lore`.

**Comment by Nightkau** [comment]
Hi, sorry it took a while to get around to testing this, this works fine for swords now but the issue remains for fishing rods, specifically. Bows seem to be fine as well.

**Comment by Skyslycer** [comment]
I'll have a look

**Comment by Skyslycer** [comment]
@Nightkau I can't reproduce it with fishing rods. Do you have a video?

**Comment by Nightkau** [comment]
We use Pyrofishing for the rods as well, I'm not sure if the augments affect the lore differently but the advanced enchantments also get visually removed. here's a video, you can see the lore stuff with enchants/augments. Bait is an advanced enchantment and Intellect is a pyrofishing augment. they disappear once another player without the wrap unlocked picks up the rod.

https://youtu.be/KKyRQbNC-34

**Comment by Skyslycer** [comment]
Can't reproduce. https://upload.skyslycer.de/wrapsbug.mp4

You might want to try asking the author what they do instead of just setting the lore.

**Comment by Skyslycer** [comment]
Hi, any updates?

**Comment by Nightkau** [comment]
Sorry, have been away. I've now opened a ticket with the plugin dev.

**Comment by Nightkau** [comment]
Hi, after speaking with the plugin dev, Pyro, we figured out what the issue itself is. when lore is added while and item is wrapped (not just augments from pyrofishing but any custom lore), and then the wrap is removed, the 'new' lore is removed, as if the lore is only saved before the item is wrapped.

**Comment by PyroTempus** [comment]
@Skyslycer I've tested this and it isn't related to PyroFishing. 

Any generic lore that is added to a 'wrapped' item will be removed from the itemstack when it is unwrapped.

It will work just fine if lore is added before an item is wrapped, but anything added while it is wrapped will not remain.

**Comment by Skyslycer** [comment]
Hmm, that's odd. In the video I sent I also add lore while it is wrapped and that remains too.

Are you sure you're on the latest 1.4.1?

**Comment by Nightkau** [comment]
https://youtu.be/wWFi7QVF-Go here's the video, and yeah the version is definitely 1.4.1. this is also what happened when testing on my live server.

**Comment by PyroTempus** [comment]
Also, if wrap-lore is set, it will remove the lore and revert it to the previous one after unwrapping. 

This is most likely the issue - not sure if your config files @Nightkau have this. I'll leave this between you two for now since I've confirmed it's not on my end.

**Comment by Skyslycer** [comment]
Thank you Pyro for the help and sorry for the inconvenience! We'll figure this out :+1:

**Comment by Nightkau** [comment]
Thanks Pyro, i can't see that line anywhere in my config files. i have lore set for the wrap when viewed in the wraps inventory but afaik that shouldn't affect the lore on the item itself.

Here's my config for one of my fishing rod wraps:

`     1:
        # The permission to virtually apply this wrap (inventory) (nullable)
        permission: 'hmcwraps.azure_fishing_rod'
        # The UUID (global identifier), has to be unique in ALL wraps!
        uuid: 'azure_fishing_rod'
        # Either custom model id or a hook to get the custom model id
        id: itemsadder:azureset:azure_fishing_rod
        # The color of the item (this won't do anything now because this isn't dye able) (nullable, just here for demonstration)
        color: '#ffffff'
        # The name in the wraps inventory
        name: '<gold><bold>Wispforged Wrap'
        # The name in the wraps inventory, if the player doesn't have the permission above (nullable)
        locked-name: '<red><bold>Locked!'
        # The lore in the wraps inventory (nullable)
        lore:
          - '<gray>Wispforged fishing rod!'
        # The lore in the wraps inventory, if the player doesn't have the permission above (nullable)
        locked-lore:
          - '<gray>You need to unlock this item!'`

**Comment by Skyslycer** [comment]
I'll try to reproduce this again.

**Comment by Nightkau** [comment]
if it helps, it specifically seems to happen when i give the item to someone who doesn't have permission for the wrap rather than it being removed through the menu. i'm not sure if it could be removing the wrap in a different way when this happens.

**Comment by Skyslycer** [comment]
I have fixed this issue and the bugfix will be released with 1.4.2. If the issue still occurs after updating, please comment on this issue again. Thank you all for being so helpful in this manner.
